apiVersion: v1
kind: Service
metadata:
  name: {{ include "nemo-agent-toolkit.fullname" . }}
  labels:
    {{- include "nemo-agent-toolkit.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- if .Values.mcp.enabled }}
    - port: {{ .Values.mcp.port }}
      targetPort: mcp
      protocol: TCP
      name: mcp
    {{- end }}
    {{- if .Values.observability.metrics.enabled }}
    - port: {{ .Values.observability.metrics.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
    {{- end }}
  selector:
    {{- include "nemo-agent-toolkit.selectorLabels" . | nindent 4 }}
