apiVersion: v2
name: nemo-agent-toolkit
description: NVIDIA NeMo Agent Toolkit - An open-source library for efficiently connecting and optimizing teams of AI agents
type: application
version: 1.0.0
appVersion: "1.2.1"
keywords:
  - nvidia
  - nemo
  - agent
  - toolkit
  - ai
  - llm
  - mcp
home: https://github.com/NVIDIA/NeMo-Agent-Toolkit
sources:
  - https://github.com/NVIDIA/NeMo-Agent-Toolkit
maintainers:
  - name: NVIDIA
    email: support@nvidia.com
