apiVersion: apps/v1
kind: Deployment
metadata:
  name: attu
  namespace: default
  labels:
    app: attu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: attu
  template:
    metadata:
      labels:
        app: attu
    spec:
      containers:
      - name: attu
        image: zilliz/attu:v2.4.0
        ports:
        - containerPort: 3000
          name: http
        env:
                - name: MILVUS_URL
                  value: "http://milvus-gpu:19530"
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: attu
  namespace: default
  labels:
    app: attu
spec:
  type: ClusterIP
  ports:
  - port: 3000
    name: http
  selector:
    app: attu
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: attu-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: attu.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: attu
            port:
              number: 3000
