apiVersion: v1
kind: Service
metadata:
  name: attu-external
  labels:
    app: attu
spec:
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30001
    protocol: TCP
  selector:
    app: attu