apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: blueprint-hostpath-storage
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: hostpath
  volumeName: blueprint-hostpath-pv
