apiVersion: v1
kind: Pod
metadata:
  name: etcd-health-check
  namespace: default
spec:
  restartPolicy: Never
  containers:
  - name: test
    image: busybox
    command: ["sh", "-c", "echo 'Testing etcd connectivity...' && nc -zv etcd.default.svc.cluster.local 2379 && echo 'etcd is healthy'"]
