apiVersion: v1
kind: Pod
metadata:
  name: fix-nfs-permissions
  namespace: default
spec:
  restartPolicy: Never
  containers:
  - name: fix-perms
    image: busybox
    command: ["sh", "-c", "echo 'Fixing NFS permissions...' && ls -la /mnt/nfs/ && chmod -R 755 /mnt/nfs/ && echo 'Permissions fixed'"]
    volumeMounts:
    - name: nfs-storage
      mountPath: /mnt/nfs
  volumes:
  - name: nfs-storage
    persistentVolumeClaim:
      claimName: blueprint-storage
