apiVersion: v1
kind: Pod
metadata:
  name: fix-nfs-permissions-privileged
  namespace: default
spec:
  restartPolicy: Never
  securityContext:
    runAsUser: 0
    runAsGroup: 0
    fsGroup: 0
  containers:
  - name: fix-perms
    image: busybox
    securityContext:
      privileged: true
    command: ["sh", "-c", "echo 'Fixing NFS permissions with privileged access...' && ls -la /mnt/nfs/ && chmod 755 /mnt/nfs/lost+found && chmod -R 755 /mnt/nfs/ && echo 'Permissions fixed successfully'"]
    volumeMounts:
    - name: nfs-storage
      mountPath: /mnt/nfs
  volumes:
  - name: nfs-storage
    persistentVolumeClaim:
      claimName: blueprint-storage
