apiVersion: v1
kind: Service
metadata:
  name: milvus-external
  labels:
    app: milvus
spec:
  type: NodePort
  ports:
  - name: grpc
    port: 19530
    targetPort: 19530
    nodePort: 30196
    protocol: TCP
  - name: http
    port: 9091
    targetPort: 9091
    nodePort: 30992
    protocol: TCP
  selector:
    app: milvus
