apiVersion: v1
kind: Pod
metadata:
  name: milvus-connect-test
  namespace: default
spec:
  restartPolicy: Never
  containers:
    - name: test
      image: busybox
      command: ["sh", "-c", "nc -zv milvus-gpu 19530 && echo 'Milvus port is open' && sleep 10"]
