apiVersion: v1
kind: Service
metadata:
  name: milvus-nodeport
  namespace: default
  labels:
    app: milvus
spec:
  type: NodePort
  ports:
  - name: grpc
    port: 19530
    targetPort: 19530
    nodePort: 30195
    protocol: TCP
  - name: http
    port: 9091
    targetPort: 9091
    nodePort: 30991
    protocol: TCP
  selector:
    app.kubernetes.io/name: milvus
    app.kubernetes.io/component: standalone
