apiVersion: v1
kind: Service
metadata:
  name: milvus-external-lb
  labels:
    app: milvus
spec:
  type: LoadBalancer
  ports:
  - name: grpc
    port: 19530
    targetPort: 19530
    protocol: TCP
  - name: http
    port: 9091
    targetPort: 9091
    protocol: TCP
  selector:
    app: milvus
