apiVersion: v1
kind: Service
metadata:
  name: milvus
  namespace: default
spec:
  selector:
    app: milvus-external-etcd
  ports:
    - protocol: TCP
      port: 19530
      targetPort: 19530
      name: milvus-grpc
    - protocol: TCP
      port: 9091
      targetPort: 9091
      name: milvus-http
  type: ClusterIP
