apiVersion: v1
kind: Pod
metadata:
  name: nfs-test
spec:
  nodeSelector:
    kubernetes.io/hostname: worker-node-1
  containers:
  - name: nfs-test
    image: busybox
    command: ["sh", "-c", "ping -c 3 132.145.203.0 && echo 'NFS server reachable'"]
  restartPolicy: Never
