apiVersion: v1
kind: Pod
metadata:
  name: rag-server-health-final
  namespace: default
spec:
  restartPolicy: Never
  containers:
  - name: test
    image: busybox
    command: ["sh", "-c", "echo 'Testing rag-server health with milvus hostname...' && wget -qO- http://rag-server:8081/health && echo 'rag-server health test complete'"]
