apiVersion: v1
kind: Pod
metadata:
  name: rag-health-test
  namespace: default
spec:
  restartPolicy: Never
  containers:
  - name: test
    image: busybox
    command: ["sh", "-c", "echo 'Testing rag-server health...' && wget -qO- http://rag-server:8081/health && echo 'health test complete'"]
