apiVersion: v1
kind: Service
metadata:
  name: rag-server-nodeport
  labels:
    app: rag-server
spec:
  type: NodePort
  ports:
  - port: 8081
    targetPort: 8081
    nodePort: 30081
    protocol: TCP
  selector:
    app.kubernetes.io/name: rag-server
