apiVersion: v1
kind: Pod
metadata:
  name: simple-milvus-test
  namespace: default
spec:
  restartPolicy: Never
  containers:
  - name: test
    image: busybox
    command: ["sh", "-c", "echo 'Testing Milvus connectivity...' && nc -zv milvus-external-etcd-clean 9091 && nc -zv milvus-external-etcd-clean 19530 && echo 'Milvus connectivity test complete'"]
