apiVersion: v1
kind: Pod
metadata:
  name: test-rag-health
  namespace: default
spec:
  restartPolicy: Never
  containers:
  - name: test
    image: busybox:latest
    command: ["sh", "-c"]
    args:
      - |
        echo "Testing RAG server health with dependencies..."
        wget -qO- 'http://rag-server:8081/health?check_dependencies=true'
        echo ""
        echo "Testing basic health endpoint..."
        wget -qO- 'http://rag-server:8081/health'
