apiVersion: v1
kind: Pod
metadata:
  name: test-nim-key-1
spec:
  restartPolicy: Never
  nodeSelector:
    kubernetes.io/hostname: instance-20251003-1851
  containers:
  - name: test
    image: nvcr.io/nim/nvidia/llama-3.2-nv-embedqa-1b-v2:1.6.0
    command: ["echo", "Key 1 test successful"]
    env:
    - name: NGC_API_KEY
      value: "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"
  imagePullSecrets:
  - name: ngc-secret
  tolerations:
  - key: "nvidia.com/gpu"
    operator: "Exists"
    effect: "NoSchedule"
---
apiVersion: v1
kind: Pod
metadata:
  name: test-nim-key-2
spec:
  restartPolicy: Never
  nodeSelector:
    kubernetes.io/hostname: instance-20251003-1851
  containers:
  - name: test
    image: nvcr.io/nim/nvidia/llama-3.2-nv-embedqa-1b-v2:1.6.0
    command: ["echo", "Key 2 test successful"]
    env:
    - name: NGC_API_KEY
      value: "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"
  imagePullSecrets:
  - name: ngc-secret
  tolerations:
  - key: "nvidia.com/gpu"
    operator: "Exists"
    effect: "NoSchedule"
---
apiVersion: v1
kind: Pod
metadata:
  name: test-nim-key-3
spec:
  restartPolicy: Never
  nodeSelector:
    kubernetes.io/hostname: instance-20251003-1851
  containers:
  - name: test
    image: nvcr.io/nim/nvidia/llama-3.2-nv-embedqa-1b-v2:1.6.0
    command: ["echo", "Key 3 test successful"]
    env:
    - name: NGC_API_KEY
      value: "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"
  imagePullSecrets:
  - name: ngc-secret
  tolerations:
  - key: "nvidia.com/gpu"
    operator: "Exists"
    effect: "NoSchedule"
