apiVersion: v1
kind: Pod
metadata:
  name: test-rag-openapi
  namespace: default
spec:
  restartPolicy: Never
  containers:
  - name: test
    image: busybox:latest
    command: ["sh", "-c"]
    args:
      - |
        echo "Testing RAG server OpenAPI schema..."
        wget -qO- http://rag-server:8081/openapi.json | grep -o '"paths":[^}]*' | head -1
        echo ""
        echo "Testing search endpoint with correct format..."
        wget -qO- --post-data='{"query":"test","collection_names":["hammerspace_docs"]}' --header='Content-Type:application/json' http://rag-server:8081/search || echo "Search failed"
        echo ""
        echo "Testing generate endpoint with correct format..."
        wget -qO- --post-data='{"messages":[{"role":"user","content":"test"}],"collection_names":["hammerspace_docs"]}' --header='Content-Type:application/json' http://rag-server:8081/generate || echo "Generate failed"
