apiVersion: v1
kind: Pod
metadata:
  name: test-ngc-auth
  namespace: default
spec:
  restartPolicy: Never
  imagePullSecrets:
  - name: ngc-secret
  containers:
  - name: test
    image: nvcr.io/nvidia/blueprint/rag-server:2.2.0
    command: ["echo", "NGC authentication successful"]
