apiVersion: v1
kind: Pod
metadata:
  name: test-ingestor-api
  namespace: default
spec:
  restartPolicy: Never
  containers:
  - name: test
    image: busybox:latest
    command: ["sh", "-c"]
    args:
      - |
        echo "Testing ingestor-server API endpoints..."
        
        echo "Health endpoint:"
        wget -qO- http://ingestor-server:8082/health || echo "Health failed"
        
        echo ""
        echo "OpenAPI schema:"
        wget -qO- http://ingestor-server:8082/openapi.json | head -20 || echo "OpenAPI failed"
        
        echo ""
        echo "Docs endpoint:"
        wget -qO- http://ingestor-server:8082/docs | head -5 || echo "Docs failed"
