apiVersion: v1
kind: Pod
metadata:
  name: test-rag-search
  namespace: default
spec:
  restartPolicy: Never
  containers:
  - name: test
    image: python:3.9-slim
    command: ["python3", "/home/ubuntu/test-rag-search.py"]
    volumeMounts:
    - name: test-script
      mountPath: /home/ubuntu
  volumes:
  - name: test-script
    hostPath:
      path: /home/ubuntu
      type: Directory
