apiVersion: v1
kind: Pod
metadata:
  name: test-pod-2
  labels:
    app: test-pod-2
spec:
  containers:
  - name: test-container
    image: busybox:1.35
    command: ["sleep", "3600"]
  restartPolicy: Never
