apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "aiq-research-assistant.proxyName" . }}-nginx
  labels:
    app.kubernetes.io/name: {{ include "aiq-research-assistant.name" . }}
    app.kubernetes.io/component: proxy
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  nginx.conf: |
    events {}
    http {
      server {
        listen 80;
        # Backend API
        location /api/aiq/ {
          proxy_pass {{ .Values.proxy.backendUrl }}/;
        }
        # RAG server
        location /api/rag/ {
          proxy_pass {{ .Values.proxy.ragServerUrl }}/;
        }
        # Frontend UI
        location / {
          proxy_pass http://{{ .Release.Name }}-aiq-frontend:{{ .Values.frontend.service.port }}/;
        }
      }
    }
