apiVersion: v1
kind: Service
metadata:
  name: {{ include "aiq-research-assistant.proxyName" . }}
  labels:
    app.kubernetes.io/name: {{ include "aiq-research-assistant.name" . }}
    app.kubernetes.io/component: proxy
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.proxy.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "aiq-research-assistant.name" . }}
    app.kubernetes.io/component: proxy
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.proxy.service.port }}
      targetPort: http
      {{- if and (eq .Values.proxy.service.type "NodePort") .Values.proxy.service.nodePort }}
      nodePort: {{ .Values.proxy.service.nodePort }}
      {{- end }}
