apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-aiq-frontend
  labels:
    app.kubernetes.io/name: {{ include "aiq-research-assistant.name" . }}
    app.kubernetes.io/component: frontend
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.frontend.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "aiq-research-assistant.name" . }}
    app.kubernetes.io/component: frontend
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.frontend.service.port }}
      targetPort: http
