apiVersion: v1
kind: Pod
metadata:
  name: fix-milvus-schema-langchain
  namespace: default
spec:
  restartPolicy: Never
  containers:
  - name: fix
    image: python:3.9-slim
    command: ["python3", "/scripts/fix_milvus_schema_langchain.py"]
    volumeMounts:
    - name: script-volume
      mountPath: /scripts
  volumes:
  - name: script-volume
    configMap:
      name: fix-milvus-schema-langchain-configmap
      defaultMode: 0755
