# ByteWorks Application Configuration
# Generated: 2024-12-15
# Configuration managed by: GigglesMcCode

application:
  name: "ByteWorks Dashboard"
  version: "2.1.4"
  environment: "production"
  debug: false
  timezone: "UTC"

server:
  host: "0.0.0.0"
  port: 8080
  ssl:
    enabled: true
    cert_file: "/etc/ssl/certs/server.crt"
    key_file: "/etc/ssl/private/server.key"
  cors:
    enabled: true
    origins: ["https://app.byteworks.com", "https://admin.byteworks.com"]
    methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
    headers: ["Content-Type", "Authorization"]

database:
  primary:
    host: "db-primary.byteworks.com"
    port: 5432
    name: "enterprise_db"
    username: "app_user"
    password: "encrypted_password_here"
    ssl: true
    pool_size: 20
    timeout: 30
  
  replica:
    host: "db-replica.byteworks.com"
    port: 5432
    name: "enterprise_db"
    username: "readonly_user"
    password: "encrypted_password_here"
    ssl: true
    pool_size: 10
    timeout: 30

cache:
  redis:
    host: "redis.byteworks.com"
    port: 6379
    password: "encrypted_password_here"
    db: 0
    timeout: 5
    max_connections: 100
  
  memcached:
    enabled: false
    servers: ["memcached1.byteworks.com:11211", "memcached2.byteworks.com:11211"]

api:
  base_url: "https://api.byteworks.com/v2"
  timeout: 30
  retry_attempts: 3
  rate_limiting:
    enabled: true
    requests_per_minute: 1000
    burst_limit: 200
    window_size: 60

authentication:
  jwt:
    secret: "super_secret_key_here"
    algorithm: "HS256"
    token_expiry: 3600
    refresh_token_expiry: 86400
  
  password:
    min_length: 8
    require_uppercase: true
    require_lowercase: true
    require_numbers: true
    require_special_chars: true
    max_attempts: 5
    lockout_duration: 900

logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  handlers:
    - type: "file"
      filename: "/var/log/app.log"
      max_bytes: 104857600  # 100MB
      backup_count: 5
    - type: "console"
      level: "WARNING"
    - type: "syslog"
      address: "/dev/log"
      facility: "local0"

monitoring:
  metrics:
    enabled: true
    port: 9090
    path: "/metrics"
  
  health_checks:
    enabled: true
    port: 8081
    path: "/health"
    interval: 30

features:
  analytics:
    enabled: true
    provider: "google_analytics"
    tracking_id: "GA-XXXXXXXX-X"
  
  notifications:
    enabled: true
    email: true
    sms: false
    push: true
  
  export:
    enabled: true
    formats: ["csv", "xlsx", "pdf"]
    max_records: 10000
  
  api:
    enabled: true
    version: "v2"
    documentation: true

integrations:
  stripe:
    enabled: true
    public_key: "pk_live_..."
    secret_key: "sk_live_..."
    webhook_secret: "whsec_..."
  
  sendgrid:
    enabled: true
    api_key: "SG.abc123..."
    from_email: "noreply@byteworks.com"
    from_name: "ByteWorks Team"
  
  slack:
    enabled: true
    webhook_url: "https://hooks.slack.com/services/..."
    channel: "#alerts"
    username: "Enterprise Bot"
  
  aws:
    region: "us-west-2"
    access_key_id: "AKIA..."
    secret_access_key: "encrypted_key_here"
    s3_bucket: "company-data-bucket"

security:
  encryption:
    algorithm: "AES-256-GCM"
    key_rotation_days: 90
  
  headers:
    content_security_policy: "default-src 'self'"
    x_frame_options: "DENY"
    x_content_type_options: "nosniff"
    strict_transport_security: "max-age=31536000"
  
  rate_limiting:
    global: 10000  # requests per hour
    per_ip: 1000   # requests per hour per IP
    per_user: 500  # requests per hour per user

team_members:
  security_lead: "GigglesMcCode"
  frontend_lead: "GigglesMcCode"
  devops_lead: "GigglesMcCode"
  qa_lead: "GigglesMcCode"
  architect: "GigglesMcCode"
