apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: blueprint-local-storage
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: local-storage
