apiVersion: v1
kind: PersistentVolume
metadata:
  name: blueprint-hostpath-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: hostpath
  hostPath:
    path: /mnt/blueprint-storage
    type: DirectoryOrCreate
