apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: milvus-data
  namespace: milvus
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: nfs-csi
  volumeName: blueprint-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: milvus-logs
  namespace: milvus
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs-csi
  volumeName: blueprint-pv
