apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: blueprint-storage
  namespace: milvus
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: nfs-csi
  volumeName: blueprint-pv
