apiVersion: v1
kind: Pod
metadata:
  name: monitor-ingestion-progress
  namespace: default
spec:
  restartPolicy: Never
  containers:
  - name: monitor
    image: python:3.9-slim
    command: ["sh", "-c"]
    args:
      - |
        pip install pymilvus
        python3 -c "
        from pymilvus import connections, utility
        import time
        
        def get_progress():
            try:
                connections.connect('default', host='milvus', port='19530')
                collections = utility.list_collections()
                
                print('=== INGESTION PROGRESS REPORT ===')
                print(f'Timestamp: {time.strftime(\"%Y-%m-%d %H:%M:%S UTC\", time.gmtime())}')
                print()
                
                for col in collections:
                    if utility.has_collection(col):
                        from pymilvus import Collection
                        c = Collection(col)
                        entities = c.num_entities
                        print(f'{col}: {entities:,} documents')
                
                # Get current pod logs to see processing status
                import subprocess
                try:
                    result = subprocess.run(['kubectl', 'logs', 'ingest-all-pdfs', '--tail=5'], 
                                          capture_output=True, text=True, timeout=10)
                    if result.returncode == 0:
                        lines = result.stdout.strip().split('\n')
                        for line in lines:
                            if 'Processed' in line and 'successful' in line:
                                print(f'\\nLatest Progress: {line}')
                                break
                except:
                    pass
                    
                print('\\n=== END REPORT ===')
                
            except Exception as e:
                print(f'Error: {e}')
        
        get_progress()
        "
