apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nim-cache-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-csi
  resources:
    requests:
      storage: 100Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nim-llm-service
  namespace: default
  labels:
    app: nim-llm-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nim-llm-service
  template:
    metadata:
      labels:
        app: nim-llm-service
    spec:
      nodeSelector:
        kubernetes.io/hostname: instance-20251003-1851
      containers:
      - name: nim-llm
        image: nvcr.io/nim/meta/llama3-8b-instruct:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: NGC_API_KEY
          value: "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"
        - name: NVIDIA_API_KEY
          value: "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"
        - name: NIM_CACHE_PATH
          value: "/nim-cache"
        - name: NIM_MODEL_PROFILE
          value: "auto"
        ports:
        - containerPort: 8000
          name: http
        volumeMounts:
        - name: nim-cache
          mountPath: /nim-cache
        resources:
          requests:
            nvidia.com/gpu: "1"
            memory: 24Gi
            cpu: "4"
          limits:
            nvidia.com/gpu: "1"
            memory: 48Gi
            cpu: "8"
        readinessProbe:
          httpGet:
            path: /v1/models
            port: 8000
          initialDelaySeconds: 240
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 20
        livenessProbe:
          httpGet:
            path: /v1/models
            port: 8000
          initialDelaySeconds: 360
          periodSeconds: 60
          timeoutSeconds: 10
          failureThreshold: 10
      volumes:
      - name: nim-cache
        persistentVolumeClaim:
          claimName: nim-cache-pvc
      imagePullSecrets:
      - name: ngc-secret
      tolerations:
      - key: "nvidia.com/gpu"
        operator: "Exists"
        effect: "NoSchedule"
---
apiVersion: v1
kind: Service
metadata:
  name: nim-llm-service
  namespace: default
  labels:
    app: nim-llm-service
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: nim-llm-service
