apiVersion: v1
kind: Service
metadata:
  name: rag-playground-service
  namespace: default
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30081
  selector:
    app: rag-playground
