apiVersion: v1
kind: Pod
metadata:
  name: rag-collections-test2
  namespace: default
spec:
  restartPolicy: Never
  containers:
  - name: test
    image: busybox
    command: ["sh", "-c", "echo 'Testing rag-server collections after restart...' && wget -qO- http://rag-server:8081/collections && echo 'collections test complete'"]
