apiVersion: v1
kind: Pod
metadata:
  name: run-embeddings
  namespace: default
spec:
  restartPolicy: Never
  containers:
  - name: test
    image: python:3.9-slim
    command: ["sh", "-c", "pip install pymilvus numpy && python3 /app/create_embeddings.py"]
    volumeMounts:
    - name: script-volume
      mountPath: /app
  volumes:
  - name: script-volume
    configMap:
      name: embeddings-script
