apiVersion: v1
kind: ConfigMap
metadata:
  name: simple-otel-collector-config
  namespace: default
data:
  otel-collector-config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318

    processors:
      batch:

    exporters:
      zipkin:
        endpoint: "http://zipkin:9411/api/v2/spans"

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [zipkin]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-otel-collector
  namespace: default
  labels:
    app: simple-otel-collector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-otel-collector
  template:
    metadata:
      labels:
        app: simple-otel-collector
    spec:
      containers:
      - name: otel-collector
        image: otel/opentelemetry-collector:latest
        command: ["/otelcol", "--config=/etc/otel-collector-config.yaml"]
        ports:
        - containerPort: 4317
          name: otlp-grpc
        - containerPort: 4318
          name: otlp-http
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        volumeMounts:
        - name: otel-collector-config
          mountPath: /etc/otel-collector-config.yaml
          subPath: otel-collector-config.yaml
      volumes:
      - name: otel-collector-config
        configMap:
          name: simple-otel-collector-config
---
apiVersion: v1
kind: Service
metadata:
  name: simple-otel-collector
  namespace: default
  labels:
    app: simple-otel-collector
spec:
  type: ClusterIP
  ports:
  - port: 4317
    name: otlp-grpc
  - port: 4318
    name: otlp-http
  selector:
    app: simple-otel-collector
