apiVersion: v1
kind: Pod
metadata:
  name: test-mcp-wrapper
  namespace: default
spec:
  restartPolicy: Never
  containers:
  - name: mcp-tester
    image: python:3.11-slim
    command: ["sh", "-c"]
    args:
      - |
        echo "Installing requests..."
        pip install requests
        echo "Testing Milvus MCP Wrapper..."
        python3 -c '
import requests
import json

# Test the Milvus MCP wrapper
MCP_URL = 'http://milvus-mcp-wrapper-service:8000'

print('Testing Milvus MCP Wrapper...')

# Test health endpoint
try:
    response = requests.get(f'{MCP_URL}/health', timeout=10)
    print(f'Health check: {response.status_code} - {response.json()}')
except Exception as e:
    print(f'Health check failed: {e}')

# Test root endpoint
try:
    response = requests.get(f'{MCP_URL}/', timeout=10)
    print(f'Root endpoint: {response.status_code} - {response.json()}')
except Exception as e:
    print(f'Root endpoint failed: {e}')

# Test collections endpoint
try:
    response = requests.get(f'{MCP_URL}/mcp/collections', timeout=10)
    print(f'Collections: {response.status_code} - {response.json()}')
except Exception as e:
    print(f'Collections endpoint failed: {e}')

print('MCP wrapper test completed.')
        '
