apiVersion: v1
kind: Pod
metadata:
  name: test-nv-ingest-simple-wget
spec:
  restartPolicy: Never
  containers:
  - name: test
    image: busybox:latest
    command: ["sh", "-c", "wget -qO- http://nv-ingest-simple-api:8080/health || echo 'Health endpoint failed'"]
