apiVersion: v1
kind: Pod
metadata:
  name: test-ingestor-embedding
spec:
  restartPolicy: Never
  containers:
  - name: test
    image: python:3.9-slim
    command: ["python3", "/scripts/test-ingestor-embedding.py"]
    volumeMounts:
    - name: test-script-volume
      mountPath: /scripts
  volumes:
  - name: test-script-volume
    configMap:
      name: test-ingestor-embedding-script
      defaultMode: 0755
