apiVersion: v1
kind: Pod
metadata:
  name: test-rag-api
  namespace: default
spec:
  restartPolicy: Never
  containers:
  - name: test
    image: python:3.9-slim
    command: ["python3", "/scripts/test-rag-api.py"]
    volumeMounts:
    - name: test-script
      mountPath: /scripts
  volumes:
  - name: test-script
    configMap:
      name: test-rag-api-script
      defaultMode: 0755
