apiVersion: v1
kind: Pod
metadata:
  name: test-milvus-hostname
  namespace: default
spec:
  restartPolicy: Never
  containers:
  - name: test
    image: python:3.9-slim
    command: ["sh", "-c", "pip install pymilvus && python3 -c \"from pymilvus import connections, list_collections; print('Testing simple milvus hostname...'); connections.connect('default', host='milvus', port='19530'); print('✓ milvus hostname works!'); collections = list_collections(); print(f'Collections: {collections}')\""]
