apiVersion: v1
kind: ConfigMap
metadata:
  name: rag-opentelemetry-collector-config
  namespace: default
data:
  otel-collector-config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
    processors:
      batch:
    exporters:
      zipkin:
        endpoint: http://zipkin:9411/api/v2/spans
        format: json
    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [zipkin]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rag-opentelemetry-collector
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rag-opentelemetry-collector
  template:
    metadata:
      labels:
        app: rag-opentelemetry-collector
    spec:
      containers:
      - name: otel-collector
        image: otel/opentelemetry-collector-contrib:latest
        command: ["/otelcol-contrib"]
        args: ["--config=/etc/otel-collector-config.yaml"]
        ports:
        - containerPort: 4317
          name: otlp-grpc
        - containerPort: 4318
          name: otlp-http
        volumeMounts:
        - name: config
          mountPath: /etc/otel-collector-config.yaml
          subPath: otel-collector-config.yaml
      volumes:
      - name: config
        configMap:
          name: rag-opentelemetry-collector-config
---
apiVersion: v1
kind: Service
metadata:
  name: rag-opentelemetry-collector
  namespace: default
spec:
  selector:
    app: rag-opentelemetry-collector
  ports:
  - name: otlp-grpc
    port: 4317
    targetPort: 4317
  - name: otlp-http
    port: 4318
    targetPort: 4318
