apiVersion: batch/v1
kind: Job
metadata:
  name: test-timing-job
spec:
  template:
    spec:
      containers:
        - name: test-timing
          image: alpine:3.19
          command: ["/bin/sh", "-c"]
          args:
            - |
              set -euo pipefail
              echo "=== TIMING TEST STARTED ==="
              START_TIME=$(date +%s)
              echo "Start time: $(date)"
              
              # Install curl
              apk add --no-cache curl coreutils
              
              # Create test files
              echo "Test document 1 content for timing analysis" > /tmp/doc1.txt
              echo "Test document 2 content for timing analysis" > /tmp/doc2.txt
              echo "Test document 3 content for timing analysis" > /tmp/doc3.txt
              
              # Create collection
              echo "Creating collection: test_timing_collection"
              COLLECTION_CREATE_START=$(date +%s)
              curl -sf -X POST "http://ingestor-server:8082/collection" \
                -H "Content-Type: application/json" \
                -d '{"collection_name":"test_timing_collection"}' || true
              COLLECTION_CREATE_END=$(date +%s)
              echo "Collection creation time: $((COLLECTION_CREATE_END - COLLECTION_CREATE_START)) seconds"
              
              # Upload documents
              echo "Uploading documents..."
              UPLOAD_START=$(date +%s)
              
              for i in 1 2 3; do
                echo "Uploading doc$i.txt..."
                DOC_START=$(date +%s)
                curl -sf -X POST "http://ingestor-server:8082/documents" \
                  -F "documents=@/tmp/doc$i.txt" \
                  -F "data={\"collection_name\":\"test_timing_collection\"}"
                DOC_END=$(date +%s)
                echo "Doc$i upload time: $((DOC_END - DOC_START)) seconds"
              done
              
              UPLOAD_END=$(date +%s)
              echo "Total upload time: $((UPLOAD_END - UPLOAD_START)) seconds"
              
              # Wait for processing
              echo "Waiting for background processing..."
              PROCESSING_START=$(date +%s)
              
              # Check collection status periodically
              for i in {1..30}; do
                echo "Check $i/30 - Checking collection status..."
                ENTITIES=$(curl -s "http://ingestor-server:8082/collections" | grep -o '"test_timing_collection"' | wc -l || echo "0")
                if [ "$ENTITIES" -gt 0 ]; then
                  echo "Collection found in API"
                  break
                fi
                sleep 2
              done
              
              PROCESSING_END=$(date +%s)
              echo "Processing time: $((PROCESSING_END - PROCESSING_START)) seconds"
              
              # Final timing
              END_TIME=$(date +%s)
              TOTAL_TIME=$((END_TIME - START_TIME))
              
              echo "=== TIMING RESULTS ==="
              echo "Collection creation: $((COLLECTION_CREATE_END - COLLECTION_CREATE_START)) seconds"
              echo "Document upload: $((UPLOAD_END - UPLOAD_START)) seconds"
              echo "Background processing: $((PROCESSING_END - PROCESSING_START)) seconds"
              echo "Total end-to-end time: $TOTAL_TIME seconds"
              echo "=== TEST COMPLETED ==="
      restartPolicy: Never
